import type { ConfiguracionSitio } from '../tipos/contenidos';

// Los textos comerciales se guardan como configuraciones públicas para que
// puedan actualizarse desde el panel sin modificar el código del sitio.
export const TEXTOS_PREDETERMINADOS = {
  navegacion_inicio: 'Inicio',
  navegacion_catalogo: 'Stickers',
  navegacion_plantillas: 'Plantillas',
  navegacion_productos_fisicos: 'Productos físicos',
  navegacion_ayuda: 'Ayuda',
  carrito_boton: 'Mi selección',
  footer_catalogo: 'Stickers',
  footer_plantillas: 'Plantillas',
  footer_productos_fisicos: 'Productos físicos',
  footer_ayuda: 'Ayuda para clientes',
  pie_derechos_reservados: 'Todos los derechos reservados.',
  inicio_texto_destacado: 'con un toque de Sol',
  catalogo_etiqueta: 'Colecciones de Papelería de Sol',
  catalogo_titulo: 'Encontrá tu próximo favorito',
  catalogo_descripcion: 'Buscá por nombre o número, elegí una categoría y agregá tus stickers favoritos a la selección.',
  catalogo_busqueda_placeholder: 'Buscar por nombre o número…',
  catalogo_todas_categorias: 'Todas las categorías',
  catalogo_aviso_disponibilidad: 'Consultá disponibilidad por WhatsApp',
  catalogo_pagina_anterior: 'Anterior',
  catalogo_pagina_siguiente: 'Siguiente',
  plantillas_etiqueta: 'Diseños digitales',
  plantillas_titulo: 'Plantillas creativas',
  plantillas_descripcion: 'Encontrá plantillas para organizar, estudiar y crear. Elegí la que te gusta y consultanos por WhatsApp.',
  plantillas_vacio_etiqueta: 'Estamos preparando novedades',
  plantillas_vacio_titulo: 'Próximamente habrá nuevas plantillas',
  plantillas_vacio_descripcion: 'Consultanos por WhatsApp si buscás un diseño personalizado.',
  plantillas_vacio_boton: 'Consultar por WhatsApp',
  fisicos_etiqueta: 'Hechos con dedicación',
  fisicos_titulo: 'Productos físicos',
  fisicos_descripcion: 'Elegí productos de papelería creativa, regalos y opciones personalizadas. Consultá por WhatsApp para coordinar los detalles.',
  fisicos_vacio_etiqueta: 'Nuevas creaciones en camino',
  fisicos_vacio_titulo: 'Muy pronto vas a ver productos físicos',
  fisicos_vacio_descripcion: 'Mientras tanto, podés consultarnos si tenés una idea especial.',
  fisicos_vacio_boton: 'Contanos tu idea',
  producto_destacado: 'Destacado',
  producto_tipo_fisico: 'Producto físico',
  producto_agregar: 'Agregar',
  producto_agregar_seleccion: 'Agregar a mi selección',
  producto_sku: 'SKU',
  producto_categoria: 'Categoría',
  producto_disponibilidad: 'Disponibilidad',
  producto_en_stock: 'En stock',
  producto_consultar: 'Consultar',
  producto_aviso_whatsapp: 'Agregá este producto a tu selección. Por WhatsApp coordinamos la disponibilidad, el retiro o envío, el pago y otros detalles del pedido.',
  carrito_etiqueta: 'Tu pedido',
  carrito_titulo: 'Mi selección',
  carrito_vacio: 'Todavía no agregaste productos.',
  carrito_explorar_catalogo: 'Explorar stickers',
  carrito_productos_seleccionados: 'Productos seleccionados',
  carrito_total: 'Total',
  carrito_continuar_whatsapp: 'Continuar compra por WhatsApp',
  carrito_vaciar: 'Vaciar selección',
  carrito_aclaracion: 'El pedido se confirma personalmente por WhatsApp. No se realiza ningún pago desde esta página.',
  carrito_cantidad: 'Cantidad',
  carrito_agregado: 'se agregó a tu selección.',
  mensaje_whatsapp_inicio: '¡Hola! Quisiera realizar el siguiente pedido:',
  mensaje_whatsapp_total_productos: 'Total de productos',
  mensaje_whatsapp_total: 'Total del pedido',
  mensaje_whatsapp_cierre: 'Quedo atento/a. Gracias.',
  ayuda_etiqueta: 'Estamos para ayudarte',
  ayuda_titulo: 'Cómo consultar y comprar',
  ayuda_descripcion: 'Elegí tus productos, armá tu selección y escribinos por WhatsApp para coordinar los detalles.',
  ayuda_paso_1_titulo: '1. Explorá los stickers',
  ayuda_paso_1_descripcion: 'Buscá stickers por nombre o categoría. También podés recorrer las plantillas y los productos físicos.',
  ayuda_paso_2_titulo: '2. Armá tu selección',
  ayuda_paso_2_descripcion: 'Usá el botón Agregar en cada producto. Podés cambiar las cantidades o vaciar la selección cuando quieras.',
  ayuda_paso_3_titulo: '3. Continuá por WhatsApp',
  ayuda_paso_3_descripcion: 'Al continuar, se abre WhatsApp con el detalle y el total estimado de los productos elegidos.',
  ayuda_consultas_titulo: '¿Tenés una idea especial?',
  ayuda_consultas_descripcion: 'Escribinos por WhatsApp. Allí coordinamos productos personalizados, retiro o envío, pago y otros detalles.',
  ayuda_consultas_boton: 'Escribir por WhatsApp',
} as const;

export type ClaveTextoPublico = keyof typeof TEXTOS_PREDETERMINADOS;

export function obtenerTextoPublico(
  configuracion: Partial<ConfiguracionSitio> | undefined,
  clave: ClaveTextoPublico,
) {
  const valor = configuracion?.[clave];
  return typeof valor === 'string' && valor.trim()
    ? valor.trim()
    : TEXTOS_PREDETERMINADOS[clave];
}
