-- Textos públicos editables y página de ayuda.
-- Ejecutar una sola vez en el proyecto de Supabase de PRUEBAS.
-- No modifica productos, categorías ni datos de clientes.

insert into public.configuraciones_sitio (clave, valor, descripcion, publica) values
  ('navegacion_inicio', to_jsonb('Inicio'::text), 'Texto del enlace Inicio del menú', true),
  ('navegacion_catalogo', to_jsonb('Catálogo'::text), 'Texto del enlace Catálogo del menú', true),
  ('navegacion_plantillas', to_jsonb('Plantillas'::text), 'Texto del enlace Plantillas del menú', true),
  ('navegacion_productos_fisicos', to_jsonb('Productos físicos'::text), 'Texto del enlace Productos físicos del menú', true),
  ('navegacion_ayuda', to_jsonb('Ayuda'::text), 'Texto del enlace Ayuda del menú', true),
  ('carrito_boton', to_jsonb('Mi selección'::text), 'Texto del botón que abre la selección', true),
  ('footer_catalogo', to_jsonb('Catálogo completo'::text), 'Texto del enlace de catálogo en el footer', true),
  ('footer_plantillas', to_jsonb('Plantillas'::text), 'Texto del enlace de plantillas en el footer', true),
  ('footer_productos_fisicos', to_jsonb('Productos físicos'::text), 'Texto del enlace de productos físicos en el footer', true),
  ('footer_ayuda', to_jsonb('Ayuda para clientes'::text), 'Texto del enlace de ayuda en el footer', true),
  ('pie_derechos_reservados', to_jsonb('Todos los derechos reservados.'::text), 'Texto legal breve del footer', true),
  ('inicio_texto_destacado', to_jsonb('con un toque de Sol'::text), 'Parte destacada del título del inicio', true),
  ('catalogo_etiqueta', to_jsonb('Colecciones de Papelería de Sol'::text), 'Etiqueta de la página catálogo', true),
  ('catalogo_titulo', to_jsonb('Encontrá tu próximo favorito'::text), 'Título de la página catálogo', true),
  ('catalogo_descripcion', to_jsonb('Buscá por nombre o número, elegí una categoría y agregá tus stickers favoritos a la selección.'::text), 'Descripción de la página catálogo', true),
  ('catalogo_busqueda_placeholder', to_jsonb('Buscar por nombre o número…'::text), 'Ayuda del buscador de catálogo', true),
  ('catalogo_todas_categorias', to_jsonb('Todas las categorías'::text), 'Opción de todas las categorías', true),
  ('catalogo_aviso_disponibilidad', to_jsonb('Consultá disponibilidad por WhatsApp'::text), 'Aviso del catálogo', true),
  ('catalogo_pagina_anterior', to_jsonb('Anterior'::text), 'Botón de página anterior', true),
  ('catalogo_pagina_siguiente', to_jsonb('Siguiente'::text), 'Botón de página siguiente', true),
  ('plantillas_etiqueta', to_jsonb('Diseños digitales'::text), 'Etiqueta de plantillas', true),
  ('plantillas_titulo', to_jsonb('Plantillas creativas'::text), 'Título de plantillas', true),
  ('plantillas_descripcion', to_jsonb('Las nuevas colecciones aparecerán aquí cuando sean publicadas desde el dashboard.'::text), 'Descripción de plantillas', true),
  ('plantillas_vacio_etiqueta', to_jsonb('Estamos preparando novedades'::text), 'Etiqueta de plantillas sin productos', true),
  ('plantillas_vacio_titulo', to_jsonb('Próximamente habrá nuevas plantillas'::text), 'Título de plantillas sin productos', true),
  ('plantillas_vacio_descripcion', to_jsonb('Consultanos por WhatsApp si buscás un diseño personalizado.'::text), 'Descripción de plantillas sin productos', true),
  ('plantillas_vacio_boton', to_jsonb('Consultar por WhatsApp'::text), 'Botón de plantillas sin productos', true),
  ('fisicos_etiqueta', to_jsonb('Hechos con dedicación'::text), 'Etiqueta de productos físicos', true),
  ('fisicos_titulo', to_jsonb('Productos físicos'::text), 'Título de productos físicos', true),
  ('fisicos_descripcion', to_jsonb('Los productos armados y personalizados aparecerán aquí cuando se publiquen desde el dashboard.'::text), 'Descripción de productos físicos', true),
  ('fisicos_vacio_etiqueta', to_jsonb('Nuevas creaciones en camino'::text), 'Etiqueta de productos físicos sin productos', true),
  ('fisicos_vacio_titulo', to_jsonb('Muy pronto vas a ver productos físicos'::text), 'Título de productos físicos sin productos', true),
  ('fisicos_vacio_descripcion', to_jsonb('Mientras tanto, podés consultarnos si tenés una idea especial.'::text), 'Descripción de productos físicos sin productos', true),
  ('fisicos_vacio_boton', to_jsonb('Contanos tu idea'::text), 'Botón de productos físicos sin productos', true),
  ('producto_destacado', to_jsonb('Destacado'::text), 'Distintivo de producto destacado', true),
  ('producto_tipo_fisico', to_jsonb('Producto físico'::text), 'Nombre visible del tipo producto físico', true),
  ('producto_agregar', to_jsonb('Agregar'::text), 'Botón de agregar en las tarjetas', true),
  ('producto_agregar_seleccion', to_jsonb('Agregar a mi selección'::text), 'Botón de agregar en el detalle', true),
  ('producto_sku', to_jsonb('SKU'::text), 'Etiqueta SKU del detalle', true),
  ('producto_categoria', to_jsonb('Categoría'::text), 'Etiqueta categoría del detalle', true),
  ('producto_disponibilidad', to_jsonb('Disponibilidad'::text), 'Etiqueta disponibilidad del detalle', true),
  ('producto_en_stock', to_jsonb('En stock'::text), 'Texto para producto en stock', true),
  ('producto_consultar', to_jsonb('Consultar'::text), 'Texto para consultar disponibilidad', true),
  ('producto_aviso_whatsapp', to_jsonb('Agregá este producto a tu selección. La disponibilidad, el precio final y la entrega se confirman personalmente por WhatsApp.'::text), 'Aviso de WhatsApp en detalle de producto', true),
  ('carrito_etiqueta', to_jsonb('Tu pedido'::text), 'Etiqueta del panel de selección', true),
  ('carrito_titulo', to_jsonb('Mi selección'::text), 'Título del panel de selección', true),
  ('carrito_vacio', to_jsonb('Todavía no agregaste productos.'::text), 'Texto de selección vacía', true),
  ('carrito_explorar_catalogo', to_jsonb('Explorar catálogo'::text), 'Enlace de selección vacía', true),
  ('carrito_productos_seleccionados', to_jsonb('Productos seleccionados'::text), 'Etiqueta de cantidad de productos', true),
  ('carrito_total', to_jsonb('Total'::text), 'Etiqueta de total de dinero', true),
  ('carrito_continuar_whatsapp', to_jsonb('Continuar compra por WhatsApp'::text), 'Botón de selección hacia WhatsApp', true),
  ('carrito_vaciar', to_jsonb('Vaciar selección'::text), 'Botón para vaciar selección', true),
  ('carrito_aclaracion', to_jsonb('El pedido se confirma personalmente por WhatsApp. No se realiza ningún pago desde esta página.'::text), 'Aclaración del panel de selección', true),
  ('carrito_cantidad', to_jsonb('Cantidad'::text), 'Etiqueta de cantidad en selección', true),
  ('carrito_agregado', to_jsonb('se agregó a tu selección.'::text), 'Confirmación al agregar producto', true),
  ('mensaje_whatsapp_inicio', to_jsonb('¡Hola! Quisiera consultar por los siguientes productos de Papelería de Sol:'::text), 'Inicio del mensaje de WhatsApp', true),
  ('mensaje_whatsapp_total_productos', to_jsonb('Total de productos'::text), 'Etiqueta de total de productos en WhatsApp', true),
  ('mensaje_whatsapp_total', to_jsonb('Total'::text), 'Etiqueta de total de dinero en WhatsApp', true),
  ('mensaje_whatsapp_cierre', to_jsonb('¿Podrían confirmarme disponibilidad y precio final?'::text), 'Cierre del mensaje de WhatsApp', true),
  ('ayuda_etiqueta', to_jsonb('Estamos para ayudarte'::text), 'Etiqueta de la página de ayuda', true),
  ('ayuda_titulo', to_jsonb('Cómo consultar y comprar'::text), 'Título de la página de ayuda', true),
  ('ayuda_descripcion', to_jsonb('Elegí tus productos, armá tu selección y escribinos por WhatsApp para coordinar los detalles.'::text), 'Descripción de la página de ayuda', true),
  ('ayuda_paso_1_titulo', to_jsonb('1. Explorá el catálogo'::text), 'Título del primer paso de ayuda', true),
  ('ayuda_paso_1_descripcion', to_jsonb('Buscá stickers por nombre o categoría. También podés recorrer las plantillas y los productos físicos.'::text), 'Descripción del primer paso de ayuda', true),
  ('ayuda_paso_2_titulo', to_jsonb('2. Armá tu selección'::text), 'Título del segundo paso de ayuda', true),
  ('ayuda_paso_2_descripcion', to_jsonb('Usá el botón Agregar en cada producto. Podés cambiar las cantidades o vaciar la selección cuando quieras.'::text), 'Descripción del segundo paso de ayuda', true),
  ('ayuda_paso_3_titulo', to_jsonb('3. Continuá por WhatsApp'::text), 'Título del tercer paso de ayuda', true),
  ('ayuda_paso_3_descripcion', to_jsonb('Al continuar, se abre WhatsApp con el detalle de los productos elegidos para consultar disponibilidad.'::text), 'Descripción del tercer paso de ayuda', true),
  ('ayuda_consultas_titulo', to_jsonb('¿Tenés una idea especial?'::text), 'Título del bloque final de ayuda', true),
  ('ayuda_consultas_descripcion', to_jsonb('Escribinos por WhatsApp. Allí coordinamos productos personalizados, disponibilidad, entrega y pago.'::text), 'Descripción del bloque final de ayuda', true),
  ('ayuda_consultas_boton', to_jsonb('Escribir por WhatsApp'::text), 'Botón del bloque final de ayuda', true)
on conflict (clave) do nothing;
